#------------------------------------------------------------------------------------------------
[general]
sequence = "TLTGKTITLEVEPSDTIENVKAKIQDKEGQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGG"
secondary_structure = ""
fractionally_deuterated = true

#------------------------------------------------------------------------------------------------
[BMRB]
# BMRB tables as a text file in NMR-STAR v3.1+ format
bmrb_table_fname = "bmr18583_3.str"
target_entity = 1

#------------------------------------------------------------------------------------------------
[distance]
distance_fname = "1ubq-cc-dist.txt"
distance_cutoff = 3.9

#------------------------------------------------------------------------------------------------
[labeling]
# Which labeling scheme to be used
#  "fully", "forward", "reverse", "gl13", "gl2"
scheme = "fully"

[labeling.forward]
fw_13c_15n = []
fw_13c = []
fw_15n = []

[labeling.reverse]
rev_12c_14n = ["A", "G"]
rev_12c = ["L"]
rev_14n = ["I"]
#------------------------------------------------------------------------------------------------
[preset_experiments]
selected = [
  "N-H",
  "N-(Calpha)-Cx (residues i, i+1 & i-1)",
  "N-(Co)-Cx",
  "C-C DQ-SQ Correlation",
]

#------------------------------------------------------------------------------------------------
[custom_experiments]

#------------------------------------------------------------------------------------------------
